### PR TITLE
chore(git): Setup git hooks and a few useful dev commands as scripts

### PR DESCRIPTION
**Pull request by bahmutov**
Including commit message valid in preparation for testing, semantic-release and future new features.

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks, but:
- I don’t like angular-style commit messages;
- I like semver and dislike what you call “exact”;
- `git-issues` looks cool, but there’s no need to have it in this repo. If I’d want to use it, I’d install it globally;
- I know how to commit stuff with Git.

I understand you’d like to dogfeed you projects, but I’m not interested.

**Comment by bahmutov** [comment]
Would you reconsider this for the future work purposes? I don't doubt that you know how to commit code, but can you guarantee never to forget to run unit tests on commit? Or that no one uses "2._._" in a dependency? You have not setup ".npmrc" for example with `save-exact` so this will happen at some point.

Also, if you like the semantic versioning, then semantic-release works very well if your commit messages are really strictly formatted, at least the subject lines. This is not about angular-style, it is just a cool style, we can enforce something else.

I don't think this is about dog feeding my projects, I just liked man-n in principle and would like to build upon it, rather than writing my own. Of course I can just use `npm docs <package>` or `npm home <package>`, but your module could be used to show specific parts of readme really quickly. Like `man-n lodash pick`

**Comment by wooorm** [comment]
Thanks for clarifying, @bahmutov! Sorry about the misunderstand about dog-feeding. That was overly presumptuous of me.

I cannot prevent someone screwing up dependencies, of course. However, the chance of that is minimal in my opinion. The pain of having to change the `package.json` manifest for every small bug release makes it not worth it, in my experience. (noteworthy: I’m the author of all dependencies.)

If you like man-n (first of all: cool!) I suggest to first build upon it, updates and fixes are very welcome. Most importantly, they’re way more needed than safeguarding this very small project against possible contribution mishaps (I pride myself on keen eyes; scrutinising and amending any contributions).

**Comment by bahmutov** [comment]
No worries. man
I agree with the pain of releasing small fixes - this is why setting up semantic-release (which needs formatted commit messages in my opinion) would be so helpful. I am just laying ground work for future feature submission. I really like the demo of semantic release shown here https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release - once setup it will take the decision time, package update overhead away.

I could add a feature for displaying a portion of the readme file first, and submit again,

**Comment by wooorm** [comment]
:+1:

**Comment by bahmutov** [comment]
I wrote my own manpm https://github.com/bahmutov/manpm module for this - so no worries or code modifications

**Comment by wooorm** [comment]
Looks like great work, @bahmutov!

**Pull request closed without merging**
